export const themes = [
  { name: "Patrimoine culturel matériel et immatériel", slug: "patrimoine", description: "", color: "#8B5CF6", icon: "landmark" },
  { name: "Arts visuels et design", slug: "arts-visuels", description: "", color: "#F97316", icon: "palette" },
  { name: "Musique et industries sonores", slug: "musique", description: "", color: "#EAB308", icon: "music" },
  { name: "Littérature et édition", slug: "litterature", description: "", color: "#3B82F6", icon: "book-open" },
  { name: "Spectacle vivant", slug: "spectacle", description: "", color: "#EC4899", icon: "theater" },
  { name: "Cinéma et audiovisuel", slug: "cinema", description: "", color: "#EF4444", icon: "film" },
  { name: "Mode, artisanat et créativité", slug: "mode-artisanat", description: "", color: "#14B8A6", icon: "scissors" },
  { name: "Architecture", slug: "architecture", description: "", color: "#64748B", icon: "building-2" },
  { name: "Musées, archives et mémoire", slug: "musees-archives", description: "", color: "#A855F7", icon: "archive" },
  { name: "Numérique et industries créatives", slug: "numerique", description: "", color: "#06B6D4", icon: "cpu" },
  { name: "Politiques culturelles", slug: "politiques-culturelles", description: "", color: "#10B981", icon: "scroll-text" },
  { name: "Économie et financement de la culture", slug: "economie-culture", description: "", color: "#F59E0B", icon: "banknote" },
];

export const contributors = [
  {
    id: "contrib-mukoso",
    name: "Pr. Bienvenu Mukoso",
    title: "Anthropologue",
    institution: "Université de Kinshasa",
    function: "Professeur d'anthropologie",
    expertise: "Patrimoine immatériel, corps et société en RDC",
    bio: "Professeur d'anthropologie à l'Université de Kinshasa, ses recherches portent sur les pratiques patrimoniales liées au corps et aux parures en République démocratique du Congo.",
    photoUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=mukoso",
  },
  {
    id: "contrib-mambu",
    name: "Mme Brunelle B. Mambu",
    title: "Chercheuse",
    institution: "ABA RDC",
    function: "Chercheuse associée",
    expertise: "Industries culturelles, politiques culturelles en RDC",
    bio: "Brunelle Mambu coordonne des programmes de recherche-action sur les industries culturelles et créatives en RDC au sein de l'association ABA RDC.",
    photoUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=mambu",
  },
  {
    id: "contrib-kadiata",
    name: "Dr. Eve Kadiata",
    title: "Historienne de l'art",
    institution: "Institut des Arts de Kinshasa",
    function: "Chercheuse indépendante",
    expertise: "Histoire de l'art africain, muséologie critique",
    bio: "Docteure en histoire de l'art, elle travaille sur la circulation des œuvres congolaises et la décolonisation des musées et des archives.",
    photoUrl: "https://api.dicebear.com/7.x/notionists/svg?seed=kadiata",
  },
];

export const resources = [
  {
    id: "res-1",
    title: "Parures corporelles traditionnelles en RDC : signes, sens et transmissions",
    authors: "Pr. Bienvenu Mukoso",
    year: 2021,
    type: "Ouvrage",
    publisher: "Éditions de l'Université de Kinshasa",
    country: "RDC",
    language: "Français",
    abstract: "Cet ouvrage interroge les parures corporelles traditionnelles en République démocratique du Congo comme vecteurs de mémoire, de statut social et de transmission culturelle.",
    fullReference: "Mukoso, B. (2021). Parures corporelles traditionnelles en RDC : signes, sens et transmissions. Kinshasa : Éditions de l'Université de Kinshasa.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-mukoso",
    status: "PUBLISHED",
    themeSlugs: ["patrimoine", "mode-artisanat"],
    keywordNames: ["parures corporelles", "patrimoine immatériel", "RDC"],
    createdAt: "2025-08-15T10:00:00.000Z",
  },
  {
    id: "res-2",
    title: "Économie créative en Afrique subsaharienne : état des lieux et perspectives",
    authors: "UNESCO",
    year: 2024,
    type: "Rapport",
    publisher: "UNESCO",
    country: "Afrique subsaharienne",
    language: "Français",
    abstract: "Rapport de l'UNESCO sur la contribution des industries culturelles et créatives au développement économique en Afrique subsaharienne, avec des études de cas nationales.",
    fullReference: "UNESCO. (2024). Économie créative en Afrique subsaharienne : état des lieux et perspectives. Paris : UNESCO.",
    externalLink: "https://unesdoc.unesco.org/ark:/48223/pf0000386619",
    isAvailable: true,
    availableDocument: "",
    contributorId: "contrib-mambu",
    status: "PUBLISHED",
    themeSlugs: ["economie-culture", "politiques-culturelles"],
    keywordNames: ["économie créative", "UNESCO", "Afrique subsaharienne"],
    createdAt: "2025-08-10T10:00:00.000Z",
  },
  {
    id: "res-3",
    title: "La musique congolaise : entre tradition et modernité",
    authors: "Augustin P. Lunyalole",
    year: 2022,
    type: "Ouvrage",
    publisher: "L'Harmattan",
    country: "France / RDC",
    language: "Français",
    abstract: "Une histoire des formes musicales congolaises du rite à la rumba, en passant par la world music contemporaine.",
    fullReference: "Lunyalole, A. P. (2022). La musique congolaise : entre tradition et modernité. Paris : L'Harmattan.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-kadiata",
    status: "PUBLISHED",
    themeSlugs: ["musique", "patrimoine"],
    keywordNames: ["musique congolaise", "rumba", "tradition"],
    createdAt: "2025-08-05T10:00:00.000Z",
  },
  {
    id: "res-4",
    title: "Arts visuels en RDC : trajectoires, marchés et résistances",
    authors: "Dr. Eve Kadiata",
    year: 2023,
    type: "Article de recherche",
    publisher: "African Arts Review",
    country: "RDC",
    language: "Français",
    abstract: "Cet article analyse les trajectoires des artistes visuels congolais entre scènes locales, marchés régionaux et reconnaissance internationale.",
    fullReference: "Kadiata, E. (2023). Arts visuels en RDC : trajectoires, marchés et résistances. African Arts Review, 15(2), 45-62.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-kadiata",
    status: "PUBLISHED",
    themeSlugs: ["arts-visuels", "economie-culture"],
    keywordNames: ["arts visuels", "marché de l'art", "artistes congolais"],
    createdAt: "2025-07-28T10:00:00.000Z",
  },
  {
    id: "res-5",
    title: "Politiques culturelles en RDC : enjeux et défis post-2019",
    authors: "Mme Brunelle B. Mambu",
    year: 2023,
    type: "Rapport",
    publisher: "ABA RDC",
    country: "RDC",
    language: "Français",
    abstract: "Analyse des cadres institutionnels et des politiques publiques affectant le secteur culturel en RDC depuis la réforme ministérielle de 2019.",
    fullReference: "Mambu, B. B. (2023). Politiques culturelles en RDC : enjeux et défis post-2019. Kinshasa : ABA RDC.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-mambu",
    status: "PUBLISHED",
    themeSlugs: ["politiques-culturelles"],
    keywordNames: ["politiques culturelles", "RDC", "institutions"],
    createdAt: "2025-07-20T10:00:00.000Z",
  },
  {
    id: "res-6",
    title: "Le cinéma africain francophone : production, distribution et publics",
    authors: "Jean-Pierre Karembe",
    year: 2020,
    type: "Ouvrage",
    publisher: "Éditions L'Harmattan",
    country: "France",
    language: "Français",
    abstract: "Synthèse sur les écosystèmes cinématographiques africains francophones, de la production indépendante aux circuits de distribution alternatifs.",
    fullReference: "Karembe, J.-P. (2020). Le cinéma africain francophone : production, distribution et publics. Paris : L'Harmattan.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-mambu",
    status: "PUBLISHED",
    themeSlugs: ["cinema"],
    keywordNames: ["cinéma africain", "distribution", "francophonie"],
    createdAt: "2025-07-15T10:00:00.000Z",
  },
  {
    id: "res-7",
    title: "Spectacle vivant et création contemporaine à Kinshasa",
    authors: "Collectif K-Muondo",
    year: 2024,
    type: "Article de presse",
    publisher: "Jeune Afrique",
    country: "RDC",
    language: "Français",
    abstract: "Portrait des compagnies de théâtre et de danse contemporaine qui façonnent la scène artistique kinoise.",
    fullReference: "Collectif K-Muondo. (2024). Spectacle vivant et création contemporaine à Kinshasa. Jeune Afrique, 15 mars 2024.",
    externalLink: "https://www.jeuneafrique.com",
    isAvailable: true,
    availableDocument: "",
    contributorId: "contrib-mukoso",
    status: "PUBLISHED",
    themeSlugs: ["spectacle", "numerique"],
    keywordNames: ["théâtre", "danse", "Kinshasa"],
    createdAt: "2025-07-10T10:00:00.000Z",
  },
  {
    id: "res-8",
    title: "Littérature congolaise contemporaine : nouvelles voix et nouveaux supports",
    authors: "Marie-Claire Matumona",
    year: 2023,
    type: "Thèse",
    publisher: "Université de Liège",
    country: "Belgique",
    language: "Français",
    abstract: "Thèse de doctorat consacrée à la littérature congolaise récente, à ses modes d'édition et à ses publics numériques.",
    fullReference: "Matumona, M.-C. (2023). Littérature congolaise contemporaine : nouvelles voix et nouveaux supports. Thèse de doctorat, Université de Liège.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-kadiata",
    status: "PUBLISHED",
    themeSlugs: ["litterature", "numerique"],
    keywordNames: ["littérature congolaise", "édition", "numérique"],
    createdAt: "2025-07-05T10:00:00.000Z",
  },
  {
    id: "res-9",
    title: "Architecture coloniale et post-coloniale à Kinshasa : mémoire urbaine",
    authors: "Patrick L. Tshibangu",
    year: 2021,
    type: "Ouvrage",
    publisher: "Mardaga",
    country: "Belgique",
    language: "Français",
    abstract: "Étude architecturale et urbaine de Kinshasa, entre héritage colonial, modernisme africain et transformations contemporaines.",
    fullReference: "Tshibangu, P. L. (2021). Architecture coloniale et post-coloniale à Kinshasa : mémoire urbaine. Bruxelles : Mardaga.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-mukoso",
    status: "PUBLISHED",
    themeSlugs: ["architecture", "musees-archives"],
    keywordNames: ["architecture", "Kinshasa", "mémoire urbaine"],
    createdAt: "2025-06-28T10:00:00.000Z",
  },
  {
    id: "res-10",
    title: "Industries créatives numériques en Afrique centrale : startups, plateformes et politiques",
    authors: "Brunelle B. Mambu, Aimé Kalombo",
    year: 2024,
    type: "Rapport",
    publisher: "ABA RDC / LAZIIR Group",
    country: "RDC",
    language: "Français",
    abstract: "Rapport exploratoire sur les startups culturelles numériques, les plateformes de diffusion et les besoins en politiques publiques en Afrique centrale.",
    fullReference: "Mambu, B. B., & Kalombo, A. (2024). Industries créatives numériques en Afrique centrale : startups, plateformes et politiques. Kinshasa : ABA RDC / LAZIIR Group.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-mambu",
    status: "PUBLISHED",
    themeSlugs: ["numerique", "economie-culture"],
    keywordNames: ["industries créatives", "startups", "numérique"],
    createdAt: "2025-06-20T10:00:00.000Z",
  },
  {
    id: "res-11",
    title: "Musées et décolonisation : retourner le regard sur les collections congolaises",
    authors: "Dr. Eve Kadiata",
    year: 2022,
    type: "Article de recherche",
    publisher: "Museum International",
    country: "International",
    language: "Français",
    abstract: "Article portant sur les enjeux de la restitution et de la réappropriation des collections congolaises détenues dans les musées européens.",
    fullReference: "Kadiata, E. (2022). Musées et décolonisation : retourner le regard sur les collections congolaises. Museum International, 74(1-2), 112-128.",
    externalLink: "https://www.museum-international.com",
    isAvailable: true,
    availableDocument: "",
    contributorId: "contrib-kadiata",
    status: "PUBLISHED",
    themeSlugs: ["musees-archives", "politiques-culturelles"],
    keywordNames: ["musées", "décolonisation", "restitution"],
    createdAt: "2025-06-15T10:00:00.000Z",
  },
  {
    id: "res-12",
    title: "Artisanat créatif et mode en RDC : entre héritage et innovation",
    authors: "Claudine M. Bolamba",
    year: 2023,
    type: "Article de presse",
    publisher: "Le Potentiel",
    country: "RDC",
    language: "Français",
    abstract: "Article de presse sur les créateurs de mode et d'artisanat qui réinventent les savoir-faire traditionnels congolais à Kinshasa et Lubumbashi.",
    fullReference: "Bolamba, C. M. (2023). Artisanat créatif et mode en RDC : entre héritage et innovation. Le Potentiel, 22 avril 2023.",
    externalLink: "https://www.lepotentiel.com",
    isAvailable: true,
    availableDocument: "",
    contributorId: "contrib-mukoso",
    status: "PUBLISHED",
    themeSlugs: ["mode-artisanat", "economie-culture"],
    keywordNames: ["artisanat", "mode", "innovation"],
    createdAt: "2025-06-10T10:00:00.000Z",
  },
  {
    id: "res-13",
    title: "Le financement des industries culturelles et créatives : guide à l'usage des porteurs de projets africains",
    authors: "OIF, Africalia",
    year: 2022,
    type: "Rapport",
    publisher: "OIF",
    country: "France / Belgique",
    language: "Français",
    abstract: "Guide pratique présentant les dispositifs de financement accessibles aux projets culturels et créatifs en Afrique francophone.",
    fullReference: "OIF, Africalia. (2022). Le financement des industries culturelles et créatives : guide à l'usage des porteurs de projets africains. Paris : OIF.",
    externalLink: "https://www.oif.fr",
    isAvailable: true,
    availableDocument: "",
    contributorId: "contrib-mambu",
    status: "PUBLISHED",
    themeSlugs: ["economie-culture", "politiques-culturelles"],
    keywordNames: ["financement", "guide", "projets culturels"],
    createdAt: "2025-06-05T10:00:00.000Z",
  },
  {
    id: "res-14",
    title: "Patrimoine immatériel de la République démocratique du Congo : inventaire critique",
    authors: "Ministère de la Culture et des Arts de la RDC",
    year: 2020,
    type: "Document institutionnel",
    publisher: "Ministère de la Culture et des Arts de la RDC",
    country: "RDC",
    language: "Français",
    abstract: "Inventaire préliminaire des éléments du patrimoine immatériel congolais réalisé dans le cadre de la préparation d'une convention UNESCO.",
    fullReference: "Ministère de la Culture et des Arts de la RDC. (2020). Patrimoine immatériel de la République démocratique du Congo : inventaire critique. Kinshasa.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-mukoso",
    status: "PUBLISHED",
    themeSlugs: ["patrimoine", "politiques-culturelles"],
    keywordNames: ["patrimoine immatériel", "inventaire", "UNESCO"],
    createdAt: "2025-05-28T10:00:00.000Z",
  },
  {
    id: "res-15",
    title: "Ressources audiovisuelles et archives orales du Kasaï : méthodologie de collecte",
    authors: "Pr. Bienvenu Mukoso, Sandrine K. Tshisuaka",
    year: 2019,
    type: "Ressource audiovisuelle",
    publisher: "Centre d'Études des Cultures Kasaïennes",
    country: "RDC",
    language: "Français / Tshiluba",
    abstract: "Méthodologie et premiers résultats d'un projet d'archivage audiovisuel des pratiques orales et musicales du Kasaï.",
    fullReference: "Mukoso, B., & Tshisuaka, S. K. (2019). Ressources audiovisuelles et archives orales du Kasaï : méthodologie de collecte. Kinshasa : Centre d'Études des Cultures Kasaïennes.",
    externalLink: "",
    isAvailable: false,
    availableDocument: "",
    contributorId: "contrib-mukoso",
    status: "PUBLISHED",
    themeSlugs: ["musees-archives", "musique", "patrimoine"],
    keywordNames: ["archives orales", "Kasaï", "audiovisuel"],
    createdAt: "2025-05-20T10:00:00.000Z",
  },
];

export const activities = [
  {
    id: "act-1",
    title: "Atelier documentaire #01 — Corps, parures corporelles et patrimoine culturel en RDC",
    date: "2026-08-31T10:30:00.000Z",
    endDate: "2026-08-31T13:00:00.000Z",
    type: "Atelier documentaire",
    description: "Premier atelier de revue documentaire du CRK-ICC consacré aux parures corporelles et au patrimoine culturel en RDC. L'atelier réunira chercheurs, artistes et professionnels de la documentation.",
    visualUrl: "",
    partners: "Silikin Village (ESRI), Université de Kinshasa, ABA RDC",
    report: "",
    isOnline: false,
    location: "Silikin Village (ESRI), Kinshasa",
  },
  {
    id: "act-2",
    title: "Rencontre CCIL Saint-Luc Anvers - KdG",
    date: "2026-10-26T10:00:00.000Z",
    endDate: "2026-10-26T12:00:00.000Z",
    type: "Rencontre",
    description: "Rencontre entre le CRK-ICC, les équipes de Saint-Luc Anvers et la KdG autour des collaborations académiques et artistiques.",
    visualUrl: "",
    partners: "Saint-Luc Anvers, KdG",
    report: "",
    isOnline: true,
    location: "En ligne",
  },
  {
    id: "act-3",
    title: "Table ronde — Financement des ICC en RDC",
    date: "2026-11-15T14:00:00.000Z",
    endDate: "2026-11-15T16:30:00.000Z",
    type: "Table ronde",
    description: "Table ronde réunissant opérateurs culturels, bailleurs de fonds et chercheurs pour discuter des modèles de financement des industries culturelles et créatives en RDC.",
    visualUrl: "",
    partners: "CRK-ICC, LAZIIR Group",
    report: "",
    isOnline: false,
    location: "CRK-ICC, Kinshasa",
  },
];

export const dossiers = [
  {
    id: "dossier-1",
    title: "DOSSIER #001 — Corps, parures corporelles et patrimoine culturel en RDC",
    slug: "corps-parures-patrimoine-rdc",
    description: "Premier dossier thématique issu de l'atelier de revue documentaire du 31 août 2026. Il regroupe des ressources consacrées aux parures corporelles, aux pratiques culturelles du corps et au patrimoine immatériel en République démocratique du Congo.",
    coverUrl: "",
    resourceIds: ["res-1", "res-15"],
  },
];

export const stats = {
  resourcesCount: 128,
  contributorsCount: 32,
  themesCount: 12,
  activitiesCount: 8,
};
